Area weighted R-value fix for knee walls
NREL/hescore-hpxml pull request #131
Opened 2020-12-16 04:51 UTC by bpark1327

Closes #129

2020-12-16 05:54 UTC, bpark1327 commented
Insulated knee wall:
![image](https://user-images.githubusercontent.com/59635239/102309828-eea48a80-3f26-11eb-9020-9e73d46ae895.png)

Uninsulated knee wall:
![image](https://user-images.githubusercontent.com/59635239/102309852-fbc17980-3f26-11eb-95f7-cf76a8bad244.png)
Note that an arbitrary high UA value is used for R-0 knee wall.

2020-12-22 00:00 UTC, nmerket requested changes
Looks pretty good to me. Just the one change about where to put that `get_attic_knee_wall_rvalue_and_area` method.

2020-12-22 00:00 UTC, nmerket commented on hescorehpxml/hpxml3.py
> +    def get_attic_knee_wall_rvalue_and_area(self, attic, b):
This function is identical to the one in hpxml2.py. Since it's the same in both places, it should be removed from both, placed in base.py instead so it can be inherited by the sub classes.

2020-12-22 00:00 UTC, nmerket commented on tests/test_translation.py
> +        self.assertEqual(resp['building']['zone']['zone_roof'][0]['ceiling_assembly_code'], 'ecwf03')
Looks to be working as intended.

2020-12-22 00:00 UTC, nmerket commented on examples/house8.json
> +          "ceiling_assembly_code": "ecwf38",
Interesting that this one changed as it doesn't have knee walls. It doesn't seem like that should be the case. Isn't the calculation staying the same for buildings that don't have knee walls?

2020-12-22 00:00 UTC, nmerket commented on hescorehpxml/base.py
> +            atticd['attic_floor_coc_rvalue'] = attic_floor_rvalue + 0.5
Oh, right there was a slight difference in the calculation because we're not snapping it to one of the construction code values here, so there could be a difference. So, that house8 thing is probably fine.

2020-12-22 03:26 UTC, bpark1327 commented on hescorehpxml/base.py
> +            atticd['attic_floor_coc_rvalue'] = attic_floor_rvalue + 0.5
That's right. `house8` was changed because of this.

2020-12-22 04:16 UTC, bpark1327 commented on examples/house8.json
> +          "ceiling_assembly_code": "ecwf38",
The next comment explains this change.

2020-12-22 18:18 UTC, nmerket approved these changes

2020-12-22 18:18 UTC, merged

2020-12-22 18:18 UTC, nmerket commented
Thanks @bpark1327!