Translate ResStock XML Files
NREL/hescore-hpxml pull request #151
Opened 2021-06-22 23:15 UTC by aspeake

2021-06-22 23:24 UTC, shorowit commented on resstock_sfd.xml
> +          </Wall>
@aspeake I thought we were going to update the BuildResHPXML measure to automatically add the `<AtticWallType>gable</AtticWallType>` element to these walls? https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Walls/Wall/AtticWallType

2021-06-22 23:28 UTC, aspeake commented on resstock_sfd.xml
> +          </Wall>
@shorowit that would take care of this issue most likely: https://github.com/NREL/hescore-hpxml/issues/146, I'll look into it

cc @nmerket

2021-06-22 23:33 UTC, shorowit commented on resstock_sfd.xml
> +          </Wall>
It might. Though even if it does, it's probably a good idea to improve hescore-hpxml's logic regardless.

2021-07-27 21:00 UTC, nmerket commented on hescorehpxml/hpxml3.py
> +                knee_walls.append(wall)
Check and see if these changes are still necessary.

2021-07-28 15:46 UTC, aspeake commented on hescorehpxml/base.py
> +            frac_duct_area = 1.0
No - removed and tests still run successfully

2021-07-28 15:47 UTC, aspeake commented on hescorehpxml/hpxml3.py
> +                knee_walls.append(wall)
Merged in master and that seemed to clean up the diffs

2021-10-05 21:11 UTC, nmerket commented
@aspeak to clean up some of the extra files and remove the ResStock tests and add in some tests for new code added in this PR.

2022-02-15 13:48 UTC, nmerket requested changes
Very nice job. It looks like the HPXML v3 schemas got changed when they shouldn't have. Can you revert those? Also a few other comments below.

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/base.py
> +                'Failed to validate against the following HPXML schema: {}\n{}'.format(self.SCHEMA_DIR, log)
Thanks. This is a good general improvement to have.

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/base.py
>                                'wood_stove': ('cord_wood', 'pellet_wood')}
@charliepnnl @lirainer @shorowit We can handle these additional fuel types in the modeling code. Is this going to cause a problem in the API?

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/hpxml4.py
> +    SCHEMA_DIR = 'hpxml-4.0.0'
Are there no other translation difference for v4? I had someone asking if we will support it in the next release.

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/schemas/hpxml-3.0.0/BaseElements.xsd
> +			<xs:element minOccurs="0" name="AssemblyEffectiveRValue" type="AssemblyRValue">
There shouldn't be any changes in this file. It should match exactly what is [here](https://github.com/hpxmlwg/hpxml/tree/v3.0/schemas). Was this supposed to be the HPXML v4 schema?

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/schemas/hpxml-3.0.0/HPXML.xsd
> +</xs:schema>
Same here. This file shouldn't be modified.

2022-02-15 13:48 UTC, nmerket commented on hescorehpxml/schemas/hpxml-3.0.0/HPXMLDataTypes.xsd
> +			<xs:enumeration value="other heated space"/>
Again. Same here. This file shouldn't have any diffs.

2022-02-15 13:48 UTC, nmerket commented on tests/test_translation.py
> +class TestIrrelevantSurfaces(unittest.TestCase, ComparatorBase):
Nice job on some thorough unit tests.

2022-02-15 17:23 UTC, lirainer commented on hescorehpxml/base.py
>                                'wood_stove': ('cord_wood', 'pellet_wood')}
@nmerket All of these currently work with the API. Only issue is that the electric `wall_furnace` requires an efficiency input  but should not. This is addressed in https://gitlab.hescloud.net/hes-api-code/hes-api-ci/-/issues/303. Documentation needs to be updated: https://hes-documentation.labworks.org/home/api-definitions/api-methods/submit-inputs/heating. Also, note that there is functionally no difference between an electric `wall furnace` and electric `baseboard`.

2022-02-15 17:24 UTC, lirainer commented on hescorehpxml/base.py
>                                'wood_stove': ('cord_wood', 'pellet_wood')}
Also see https://github.com/NREL/OpenStudio-HEScore/issues/292

2022-02-15 21:50 UTC, aspeake commented on tests/test_translation.py
> +class TestIrrelevantSurfaces(unittest.TestCase, ComparatorBase):
Kudos to @bpark1327 for those

2022-02-15 21:56 UTC, aspeake commented on hescorehpxml/schemas/hpxml-3.0.0/BaseElements.xsd
> +			<xs:element minOccurs="0" name="AssemblyEffectiveRValue" type="AssemblyRValue">
So I was originally pulling in schema docs from https://github.com/NREL/OpenStudio-HPXML/tree/master/HPXMLtoOpenStudio/resources/hpxml_schema which I think was on a beta version 3.0, but is now v4.0. I can revert all the 3.0 changes and pull in the new files for 4.0

2022-02-15 21:57 UTC, nmerket commented on hescorehpxml/base.py
>                                'wood_stove': ('cord_wood', 'pellet_wood')}
Ok. Just wanted to make sure we weren't breaking any rules. Sounds like it'll be fine.

2022-02-15 21:57 UTC, nmerket commented on hescorehpxml/schemas/hpxml-3.0.0/BaseElements.xsd
> +			<xs:element minOccurs="0" name="AssemblyEffectiveRValue" type="AssemblyRValue">
Yes, that would be best.

2022-02-22 22:38 UTC, nmerket commented
@shorowit I think we're going to need to talk to you about what features are in the HPXML v4 that you are using in OpenStudio-HEScore and OpenStudio-HPXML. It's not clear to me which PRs in the HPXML repo are already incorporated and which are not. I don't expect all (or even most) of them to affect the HEScore translation, but we'll need to know which are already there (especially the breaking changes) if we're going to handle them in this translator.

2022-04-19 21:46 UTC, nmerket commented
I'm going to hold off on merging this until I've confirmed and tagged the next release for HEScore.

2022-11-29 23:30 UTC, aspeake commented on examples/house_resstock.xml
> +    <SoftwareProgramVersion>2.6.0-beta</SoftwareProgramVersion>
We should probably wait until resstock v2.6.0 is released, and recreate this file

2024-03-06 17:40 UTC, nmerket commented
This has been done in the hes_translator branch of OpenStudio-HEScore

2024-03-06 17:40 UTC, closed without merging