Duct blaster measurements
NREL/hescore-hpxml pull request #168
Opened 2021-10-05 23:04 UTC by bpark1327

Address NREL/OpenStudio-HEScore#280

## Pull Request Description

Adds ability to accept CFM25 duct leakage to outside value (supply + return)

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [x] Code changes (must work)
- [x] Test exercising your feature or bug fix. Check the coverage report in the build artifacts.
- [x] All other unit tests passing
- [x] Update translation docs

2021-12-08 17:18 UTC, shorowit commented
@bpark1327 Could you pull in the latest `master` and resolve the conflict? Thanks.

2021-12-08 23:14 UTC, bpark1327 commented
> @bpark1327 Could you pull in the latest `master` and resolve the conflict? Thanks.

It's done. This branch is up to date.

2021-12-15 12:06 UTC, nmerket requested changes
Reminder to self: I need to make a release of hescore-hpxml before this or any other breaking changes get merged. I think there were some things @charliepnnl wanted to get out there sooner than the January release.

2021-12-15 12:06 UTC, nmerket commented on hescorehpxml/base.py
> +        if leakage_to_outside:
Looks like preference is given to the duct blaster measurement. I think that's the right choice.

2021-12-17 15:59 UTC, nmerket approved these changes

2021-12-17 16:00 UTC, merged