Increase granularity of construction codes
NREL/hescore-hpxml pull request #187
Opened 2022-01-13 06:59 UTC by bpark1327

Fixes https://github.com/NREL/OpenStudio-HEScore/issues/208

## Pull Request Description

Increase granularity of construction codes

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Code changes (must work)
- [ ] Test exercising your feature or bug fix. Check the coverage report in the build artifacts.
- [ ] All other unit tests passing
- [ ] Update translation docs

2022-01-27 18:51 UTC, shorowit commented
@bpark1327 Can you create a branch with the same name on OS-HEScore and git subtree pull this in?

2022-01-28 18:16 UTC, shorowit commented
... and now that we have a git subtree, move the OS-HEScore/rulesets/HEScoreRuleset/resources lookup files to this repo and update the OS-HEScore ruleset to use the updated paths.

2022-02-10 21:21 UTC, shorowit requested changes

2022-02-10 22:02 UTC, shorowit commented
@bpark1327 Can you check or ~strikethrough~ the PR checklist boxes?

2022-02-11 02:00 UTC, shorowit approved these changes

2022-02-17 17:37 UTC, nmerket reviewed
How are you calculating the assembly R-values? 

Also, this is going to conflict my knee wall stuff. I think this should merge first and I can fix that over there before merging that.

2022-02-17 17:56 UTC, bpark1327 commented on hescorehpxml/base.py
You're right. Not sure why I didn't remove it. 
```suggestion
        assembly_eff_rvalue = self.get_wall_assembly_rvalue(hpxmlwall, hpxmlwall)

```

2022-02-17 18:09 UTC, bpark1327 commented
> How are you calculating the assembly R-values?

A linear correlation is expected between the cavity R-value and the assembly R-value because the assembly R-value is the cavity R-value plus a constant R-value such as air film, carpet, etc.
I found a correlation between cavity R-value and assembly R-value using the existing lookup values. Then, I used the correlation to increase the granularity of the lookup values.

2022-02-17 22:32 UTC, merged