Fix for foundation wall and slab-on-grade insulation errors
NREL/hescore-hpxml pull request #201
Opened 2022-05-31 19:38 UTC by bpark1327

Fixes #200 

## Pull Request Description

Not to throw an error if a foundation wall or slab-on-grade has both AssemblyRValue and Layer/NominalRValue elements.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Code changes (must work)
- [ ] Test exercising your feature or bug fix. Check the coverage report in the build artifacts.
- [ ] All other unit tests passing
- [ ] Update translation docs

2022-06-01 17:29 UTC, nmerket requested changes

2022-06-01 17:29 UTC, nmerket commented on hescorehpxml/base.py
>                              f'Every foundation wall insulation layer needs a NominalRValue, fwall_id = {fwallid}')
Here's the logic I'm seeing here translated into words: If the foundation wall has an AssemblyRValue _and_ none of the layers have a NominalRValue, then throw an error saying every layer needs a NominalRValue. 

I'm not clear why we're looking at assembly R-values here at all. Based on what we say we're doing in [the docs](https://hescore-hpxml.readthedocs.io/en/v6.2/translation/zone_floor.html#foundation-wall-insulation-r-value) we should just be looking at the NominalRValue of each layer.

2022-06-01 20:35 UTC, nmerket commented on hescorehpxml/base.py
>                              f'Every foundation wall insulation layer needs a NominalRValue, fwall_id = {fwallid}')
Ah, okay. I see where that came from now. Let's change this so it will look for NominalRValue and throw an error if it's not there because the way it is, the error doesn't really make sense.

2022-06-01 23:41 UTC, nmerket commented on hescorehpxml/base.py
>                              f'Every foundation wall insulation layer needs a NominalRValue, fwall_id = {fwallid}')
Make sure it's there and set to 0.

2022-06-03 04:11 UTC, bpark1327 commented on hescorehpxml/base.py
> +                            xpath(fwall, 'count(h:Insulation/h:Layer)'):
@nmerket I created similar functions for foundation walls and slabs in hpxml2 and hpxml3. Please let me know what you think.

2022-06-03 13:20 UTC, shorowit commented on hescorehpxml/base.py
> +                            xpath(fwall, 'count(h:Insulation/h:Layer)'):
@bpark1327 If you find yourself copying and pasting blocks of code, or have blocks of code that are virtually identical, pause and think if there's a better way.

In this case...
1. The methods you added to hpxml2.py and hpxml3.py are 100% identical. Move them to the base class instead.
2. The slab vs fwall methods are 99% identical. Combine them into a single method that takes in an argument to handle the one difference in the xpath query.

2022-06-03 16:44 UTC, bpark1327 commented on hescorehpxml/base.py
> +                            xpath(fwall, 'count(h:Insulation/h:Layer)'):
@shorowit Thanks for your advice. That's something I should always aim for.

2022-06-06 17:21 UTC, merged