Geometry and Envelope Additions
NREL/hescore-hpxml pull request #216
Opened 2023-02-22 16:37 UTC by bpark1327

Fixes #

## Pull Request Description

Reflect changes applied to [a PR in OS-HEScore](https://github.com/NREL/OpenStudio-HEScore/pull/367)

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Code changes (must work)
- [ ] Test exercising your feature or bug fix. Check the coverage report in the build artifacts.
- [ ] All other unit tests passing
- [ ] Update translation docs

2023-02-27 22:58 UTC, bpark1327 commented
@nmerket I don't know why test (3.6) fails. Please advise.

2023-02-27 23:50 UTC, nmerket commented
Python 3.6 is [end of life](https://devguide.python.org/versions/) and no longer getting support. Let's remove it from the [python version list](https://github.com/NREL/hescore-hpxml/blob/geometry_envelope_additions/.github/workflows/build-test.yml#L9) on CI. While we're at it, we should probably add 3.10 and 3.11 to that list instead.

2023-02-28 16:02 UTC, bpark1327 commented on examples/townhouse_walls_v3.xml
> +                    </Wall>
@nmerket Do you expect to always see at least 4 walls in HPXML? Or do we need to make assumptions when there are fewer than 4 walls?

2023-02-28 16:38 UTC, nmerket commented on examples/townhouse_walls_v3.xml
> +                    </Wall>
No, there can be any number of walls in HPXML. See [these docs](https://hescore-hpxml.readthedocs.io/en/v7.0.2/translation/zone_wall.html#wall-orientation) for how we try to flexibly support many different wall configurations.

2023-03-03 20:36 UTC, bpark1327 commented on examples/townhouse_walls_v3.xml
> +                    </Wall>
See https://github.com/NREL/OpenStudio-HEScore/pull/385#issuecomment-1453923621

2023-03-15 15:36 UTC, nmerket requested changes
See my comments and questions below. Looks mostly good, I'd like to see some more testing of the capabilities we've added such test files for mobile homes and apartments and a couple permutations of the input possibilities there.

2023-03-15 15:36 UTC, nmerket commented on examples/hescore_min_v3.json
We should remove this file. This should be equivalent to hescore_min.json. It's being tested against that file. Likewise we should remove all the house*_v3.json files and the house1-v2*.json files as they should be equivalent to the other ones.

We should update the create_all_example_json.py file to only create the ones we expect for the tests.

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/base.py
> +            if is_exterior_wall:
What happens if the wall _isn't_ an exterior wall? It looks like it could still try to make a construction code and it an error because `sidingtype` doesn't get set.

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/base.py
> +                raise TranslationError('%s has no orientation information.' % (wall_id))
In a lot of cases you don't need to catch the `ElementNotFoundError` as it will return the xpath of the element it was looking for and didn't find in the error message. It's subclassed from `TranslationError` so it will be caught at the higher level and returned without a gross Traceback.

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/base.py
> +        #         if window_on_shared_wall_fail:
Can we delete this commented out code?

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/base.py
> +            if len(windows) == 0:  # FIXME: Do we need this?
You're right. It looks like this is no longer necessary. In OpenStudio-HEScore we [check if the side has windows](https://github.com/NREL/OpenStudio-HEScore/blob/d7400f92f128659d9bd7c2704c0e9e0c774a974c/rulesets/HEScoreRuleset/resources/HESruleset.rb#L384) and skip them if the `zone_window` key isn't there. I think the better thing to do would be to just omit the `zone_window` key if there are no windows.

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/hpxml2.py
> +                                 'other': None}  # FIXME: Check it
What happens with `None` here?

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/lookups/make_lu_eff_rvalue.py
> +    int_wall_asssembly_codes = ["iwwf00", "iwwf03", "iwwf07", "iwwf11", "iwwf13", "iwwf15", "iwwf19", "iwwf21"]
For knee walls I'm pulling these from the json schema. I think it'd be good to do that here too so we don't have to maintain this list in two places.

2023-03-15 15:36 UTC, nmerket commented on hescorehpxml/schemas/hescore_json.schema.json
> +                                        {"$ref": "#/definitions/def_left_window_constraint"}
Do these still apply?

2023-03-15 15:36 UTC, nmerket commented on tests/test_translation.py
I see removing a lot of tests that aren't relevant anymore, but I'd like to see some new tests, especially of building types that we are adding: mobile homes and apartments.

2023-03-22 15:16 UTC, bpark1327 commented on hescorehpxml/hpxml2.py
> +                                 'other': None}  # FIXME: Check it
I can change it to raise TranslationError when it returns None. What do you think?

2023-03-22 15:37 UTC, nmerket commented on hescorehpxml/hpxml2.py
> +                                 'other': None}  # FIXME: Check it
I'm a little lost in the context, but yeah, if there's no other reasonable assumption we should do here. Whatever you decide make sure this ends up in the translation documentation.

2023-03-27 22:11 UTC, shorowit commented on docs/source/translation/zone_wall.rst
> +   other housing unit below    other_unit
Doesn't seem like these two enumerations should be used for a _wall_; they only make sense for a floor or ceiling.

2023-03-29 16:24 UTC, merged

2023-03-29 16:46 UTC, bpark1327 commented on hescorehpxml/schemas/hescore_json.schema.json
> +                                        {"$ref": "#/definitions/def_left_window_constraint"}
@nmerket I gave another thought to this. I think we still need to check all of these. But these constraints are overly complicated. I added these to zone_wall level https://github.com/NREL/hescore-hpxml/blob/29df54370a078b6425d2140087f6838e1fae2de1/hescorehpxml/schemas/hescore_json.schema.json#L1058-L1114
It's not going to return user-friendly error messages as before but I think it is sufficient.