HVAC and DHW efficiency units
NREL/hescore-hpxml pull request #222
Opened 2023-04-26 22:37 UTC by yzhou601

Fixes #

## Pull Request Description

description here

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Code changes (must work)
- [ ] Test exercising your feature or bug fix. Check the coverage report in the build artifacts.
- [ ] All other unit tests passing
- [ ] Update translation docs

2023-05-02 20:22 UTC, nmerket requested changes

2023-05-02 22:14 UTC, nmerket commented on hescorehpxml/schemas/hescore_json.schema.json
>                                                  }
Ok. Maybe I'm just having a hard time following what's going on in JSON Schema land. It wouldn't be the first time.

2023-05-02 23:05 UTC, shorowit commented on hescorehpxml/base.py
>                          assert sys_heating['efficiency_method'] == 'shipment_weighted'
@nmerket Should we remove all of these `do_bounds_check` now that they are enforced in the schema (e.g., [here](https://github.com/NREL/hescore-hpxml/blob/1b94e405582a7c9bd82415bc09cab2aa01af6325/hescorehpxml/schemas/hescore_json.schema.json#L1142-L1145))? (Does hescore-hpxml validate the JSON that it produces?)

Seems like we should be moving away from doing validation multiple places, since the bounds can become inconsistent between the schema and here. If for some reason these error checks need to remain in python, could we read the min/max values from the JSON instead?

(This comment applies to DHW efficiency bounds below and maybe other things too.)

2023-05-02 23:08 UTC, nmerket commented on hescorehpxml/base.py
>                          assert sys_heating['efficiency_method'] == 'shipment_weighted'
That's a great idea to remove them from here.

2023-05-02 23:57 UTC, bpark1327 commented on hescorehpxml/schemas/hescore_json.schema.json
>                                                  }
It is confusing. Maybe there is a better way to do this. I'll think about it.

2023-05-03 03:22 UTC, yzhou601 commented on hescorehpxml/base.py
> +                sys_heating['efficiency_unit'] = eff_unit_els[0].lower()
Good catch Noel! Yes it's accidentally keeping the previous approach of searching the first element. I'll change it to search with a preference. But is it fine to use HSPF2 over HSPF? In my understanding, HSPF2 is converted to HSPF in the OS-HPXML workflow and being modeled with HSPF afterwards.

2023-05-03 04:42 UTC, yzhou601 commented on tests/test_translation.py
> +        """
No, the schema used is still 3.0 since the 3.1 branch is still pending.

2023-05-03 13:32 UTC, shorowit commented on hescorehpxml/base.py
> +                sys_heating['efficiency_unit'] = eff_unit_els[0].lower()
Someday we will probably have a separate HSPF2/SEER2 model, the current approach is just an interim solution. I agree with Noel that you should give preference to the newest metrics.

2023-05-03 15:05 UTC, nmerket commented on tests/test_translation.py
> +        """
Ah, yes, we should get the 3.1 branch in place here. What if we merge https://github.com/NREL/hescore-hpxml/pull/219 into this branch then move forward from there?

2023-05-04 15:26 UTC, nmerket reviewed
This looks good to me. One small request below for a test.

2023-05-05 19:05 UTC, yzhou601 commented
@nmerket  One more thing, I will update the doc for the preferred units.

2023-05-05 19:07 UTC, nmerket submitted a review, later dismissed

2023-06-01 19:48 UTC, nmerket commented
@yzhou601 It seems the HPXML 3.1 changes got undone somewhere along the line around `77015025e58da6a3417dfb03598db6de99e84831`, so this is still using HPXML v3.0.

2023-06-20 16:58 UTC, nmerket approved these changes

2023-06-20 16:58 UTC, merged